In [11]:
#Importing the libraries
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score



In [2]:
spreadsheet=pd.read_csv("ml-task-data - candy-data.csv")
print(spreadsheet)


   Class  Feature 1  Feature 2  Feature 3  Feature 4  Feature 5  Feature 6  \
0     C1          1          0          1          0          0          1   
1     C2          1          0          0          0          1          0   
2     C3          0          0          0          0          0          0   
3     C4          0          0          0          0          0          0   
4     C5          0          1          0          0          0          0   
..   ...        ...        ...        ...        ...        ...        ...   
80   C81          0          1          0          0          0          0   
81   C82          0          1          0          0          0          0   
82   C83          0          1          0          0          0          0   
83   C84          0          0          1          0          0          0   
84   C85          1          0          0          0          0          1   

    Feature 7  Feature 8  Feature 9  Feature 10  Feature 11  Fe

In [3]:
spreadsheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Class       85 non-null     object 
 1   Feature 1   85 non-null     int64  
 2   Feature 2   85 non-null     int64  
 3   Feature 3   85 non-null     int64  
 4   Feature 4   85 non-null     int64  
 5   Feature 5   85 non-null     int64  
 6   Feature 6   85 non-null     int64  
 7   Feature 7   85 non-null     int64  
 8   Feature 8   85 non-null     int64  
 9   Feature 9   85 non-null     int64  
 10  Feature 10  85 non-null     float64
 11  Feature 11  85 non-null     float64
 12  Feature 12  85 non-null     float64
dtypes: float64(3), int64(9), object(1)
memory usage: 8.8+ KB


In [4]:
from sklearn.model_selection import train_test_split
X=spreadsheet.drop(['Class'], axis=1)
Y=spreadsheet['Class']

In [5]:
X

Feature 1  Feature 2  Feature 3  Feature 4  Feature 5  Feature 6  \
0           1          0          1          0          0          1   
1           1          0          0          0          1          0   
2           0          0          0          0          0          0   
3           0          0          0          0          0          0   
4           0          1          0          0          0          0   
..        ...        ...        ...        ...        ...        ...   
80          0          1          0          0          0          0   
81          0          1          0          0          0          0   
82          0          1          0          0          0          0   
83          0          0          1          0          0          0   
84          1          0          0          0          0          1   

    Feature 7  Feature 8  Feature 9  Feature 10  Feature 11  Feature 12  
0           0          1          0       0.732       0.860   66.971725  
1           0          1          0       0.604       0.511   67.602936  
2           0          0          0       0.011       0.116   32.261086  
3           0          0          0       0.011       0.511   46.116505  
4           0          0          0       0.906       0.511   52.341465  
..        ...        ...        ...         ...         ...         ...  
80          0          0          0       0.220       0.116   45.466282  
81          1          0          0       0.093       0.116   39.011898  
82          0          0          1       0.313       0.313   44.375519  
83          1          0          0       0.186       0.267   41.904308  
84          0          0          1       0.872       0.848   49.524113  

[85 rows x 12 columns]

In [6]:
Y

0      C1
1      C2
2      C3
3      C4
4      C5
     ... 
80    C81
81    C82
82    C83
83    C84
84    C85
Name: Class, Length: 85, dtype: object

In [34]:
#Replace Zeros

zero_not_accepted=['Feature 10','Feature 11','Feature 12']

for column in zero_not_accepted:
    spreadsheet[column]=spreadsheet[column].replace(0, np.NaN)
    mean=int(spreadsheet[column].mean(skipna=True))
    spreadsheet[column]=spreadsheet[column].replace(np.NaN,mean)

In [35]:
#Split Dataset

X=spreadsheet.iloc[:, 1:13]
Y=spreadsheet.iloc[:, 1]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [36]:
#Feature Scaling
sc_x= StandardScaler()    
X_train= st_x.fit_transform(X_train)    
X_test= st_x.transform(X_test)  

In [37]:
import math
math.sqrt(len(Y_test))

4.123105625617661

In [38]:
#Define the Model
classifier=KNeighborsClassifier(n_neighbors=3,p=85,metric="euclidean")

In [44]:
#Fit Model
classifier.fit(X_train,Y_train)
KNeighborsClassifier(algorithm='auto',leaf_size=30, metric='euclidean',
                    metric_params=None,n_jobs=1,n_neighbors=3,p=85,weights='uniform')

KNeighborsClassifier(metric='euclidean', n_jobs=1, n_neighbors=3, p=85)

In [45]:
#Predict the test set results
Y_pred=classifier.predict(X_test)
Y_pred

array(['C32', 'C34', 'C22', 'C22', 'C43', 'C18', 'C25', 'C43', 'C24',
       'C23', 'C22', 'C18', 'C17', 'C30', 'C2', 'C43', 'C16'],
      dtype=object)

In [41]:
#Evaluate Model
cm=confusion_matrix(Y_test,Y_pred)
print(cm)

[[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 

In [46]:
print(f1_score(Y_test, Y_pred))

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [43]:
print(accuracy_score(Y_test,Y_pred))

0.0
